export const WAIVER_VERSION = 'xform-foundation-waiver-v1'

export const WAIVER_TEXT = `IMPORTANT — PLEASE READ THIS WAIVER CAREFULLY BEFORE SUBMITTING YOUR APPLICATION:

BY JOINING THE XFORMPHYSIQUE PROGRAM, YOU ACKNOWLEDGE AND ACCEPT THE INHERENT RISKS ASSOCIATED WITH PHYSICAL TRAINING, BODY TRANSFORMATIONS, CONTEST PREPARATION, OR ANY FITNESS-RELATED ACTIVITY. YOU FULLY UNDERSTAND THAT PARTICIPATION MAY INVOLVE THE RISK OF INJURY, PHYSICAL STRAIN, OR OTHER HEALTH ISSUES, AND YOU AGREE TO TAKE FULL RESPONSIBILITY FOR YOUR OWN HEALTH AND SAFETY.

YOU HEREBY RELEASE, WAIVE, AND DISCHARGE XFORMPHYSIQUE AND ALL ITS COACHES, TEAM MEMBERS, ASSOCIATES, AND REPRESENTATIVES FROM ANY LIABILITY — NOW OR IN THE FUTURE — FOR ANY PHYSICAL OR MEDICAL COMPLICATIONS THAT MAY ARISE DURING OR AFTER YOUR PARTICIPATION IN OUR PROGRAMS.

YOU CONFIRM THAT YOU ARE ENROLLING WILLINGLY, WITHOUT FORCE OR PRESSURE, AND HAVE HAD THE OPPORTUNITY TO ASK QUESTIONS REGARDING YOUR HEALTH, THE PROGRAM STRUCTURE, AND ALL RELATED SERVICES.

FURTHERMORE, YOU AGREE THAT ALL PAYMENTS MADE TOWARD COACHING, CONSULTATION, OR ANY SERVICE BY XFORMPHYSIQUE ARE FINAL AND NON-REFUNDABLE, REGARDLESS OF CIRCUMSTANCE.

BY SUBMITTING THIS FORM, YOU DECLARE THAT ALL INFORMATION SHARED BY YOU IS HONEST, ACCURATE, AND COMPLETE TO THE BEST OF YOUR KNOWLEDGE. YOU FULLY UNDERSTAND AND AGREE TO ALL TERMS LISTED ABOVE.

DO YOU AGREE TO THE TERMS OF THIS WAIVER AND FULLY ACCEPT RESPONSIBILITY FOR YOUR PARTICIPATION?`
