import { test, expect } from '@playwright/test'
import { metrics, tinyImage, progressFixture, mockProgress, loginProgress } from './progress-fixture'

const nav = page => page.getByRole('navigation', { name: 'Client navigation', exact: true })

test('every exercise/set persists on navigation; deleting a set changes saved volume', async ({ page }, info) => {
  const state = progressFixture(); await mockProgress(page, 'client', state); await loginProgress(page)
  await nav(page).getByRole('button', { name: 'Workout', exact: true }).click()
  for (const name of ['Goblet squat', 'Romanian deadlift']) for (const n of [1, 2]) {
    await page.getByLabel(`${name} set ${n} reps`, { exact: true }).fill('10')
    await page.getByLabel(`${name} set ${n} load`, { exact: true }).fill(n === 1 ? '20' : '25')
  }
  await expect(page.getByText('Total: 900 kg', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  await expect(page.getByText('Draft saved. You can continue later.')).toBeVisible()
  expect(state.workout.exercises.flatMap(e => e.sets)).toHaveLength(4)
  await nav(page).getByRole('button', { name: 'Dashboard', exact: true }).click()
  await nav(page).getByRole('button', { name: 'Workout', exact: true }).click()
  await expect(page.getByLabel('Romanian deadlift set 2 load', { exact: true })).toHaveValue('25')
  await page.getByRole('button', { name: 'Remove Goblet squat set 2', exact: true }).click()
  await expect(page.getByText('Total: 650 kg', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Complete session', exact: true }).click()
  await expect(page.getByText('Session completed and saved.')).toBeVisible()
  expect(state.workout.exercises[0].sets).toHaveLength(1)
  await page.getByText('Complete set history', { exact: true }).click()
  await expect(page.getByRole('cell', { name: '200', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('workout-sets-and-history.png'), fullPage: true })
  expect(state.errors).toEqual([])
})

test('expanded check-in and per-week coach feedback round-trip without changing old answers', async ({ page, browser }, info) => {
  const state = progressFixture(); await mockProgress(page, 'client', state); await loginProgress(page)
  await nav(page).getByRole('button', { name: 'Check-ins', exact: true }).click()
  await page.locator('[name="energy_score"]').selectOption('4'); await page.locator('[name="sleep_score"]').selectOption('3')
  for (const metric of metrics) await page.locator(`[name="${metric}"]`).selectOption(metric === 'hunger' ? '3' : '8')
  await page.locator('[name="sentiment"]').selectOption('good')
  await page.getByLabel('What went well?', { exact: true }).fill('Two strength sessions and consistent meals.')
  await page.getByLabel('Challenges', { exact: true }).fill('One late work evening.')
  await page.getByRole('button', { name: 'Submit check-in', exact: true }).click()
  await expect(page.getByText('This week’s check-in saved. Previous weeks are unchanged.')).toBeVisible()
  expect(state.checkins).toHaveLength(2); expect(state.checkins[1].energy_score).toBe(4); expect(state.checkins[1].ratings).toEqual({})
  expect(state.checkins[0].ratings.hunger).toBe(3)
  const context = await browser.newContext(); const coach = await context.newPage()
  await mockProgress(coach, 'coach', state); await loginProgress(coach, 'Coach')
  await coach.getByRole('button', { name: 'Review Navaneet Deshpande', exact: true }).click()
  await coach.getByText('Week 2026-09-07 · good · Awaiting coach review', { exact: true }).click()
  const currentReview = coach.locator('.weekly-record[open]')
  for (const [label, text] of [['Observations','Consistent sessions.'],['Adjustments','Maintain current load.'],['Instructions','Keep reps controlled.'],['Next-week priorities','Earlier bedtime.']]) await currentReview.getByLabel(label, { exact: true }).fill(text)
  await currentReview.getByRole('button', { name: 'Save weekly feedback', exact: true }).click()
  await expect(coach.getByText('Feedback saved to this client and week only.')).toBeVisible()
  await expect(coach.locator('.photo-week-notes')).toContainText('Consistent sessions.')
  await expect(coach.locator('.photo-week-notes')).toContainText('Earlier bedtime.')
  await coach.screenshot({ path: info.outputPath('coach-weekly-review.png'), fullPage: true })
  await nav(page).getByRole('button', { name: 'Dashboard', exact: true }).click()
  await nav(page).getByRole('button', { name: 'Check-ins', exact: true }).click()
  await page.getByText('Week 2026-09-07 · good · Reviewed', { exact: true }).click()
  await expect(page.getByText('Earlier bedtime.', { exact: true })).toBeVisible()
  expect(state.checkins[1].feedback).toBeUndefined()
  await context.close(); expect(state.errors).toEqual([])
})

test('all five poses compare by week; zoom, replace and delete affect only selected photo', async ({ page }, info) => {
  const state = progressFixture(); await mockProgress(page, 'client', state); await loginProgress(page)
  await nav(page).getByRole('button', { name: 'Progress Photos', exact: true }).click()
  for (const pose of ['Front','Back','Side','Front Double Bicep','Back Double Bicep']) {
    await page.getByRole('button', { name: pose, exact: true }).click()
    await expect(page.locator('.weekly-photo-pair img')).toHaveCount(2)
    await page.locator('.weekly-photo-pair .photo-image-button').last().click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('button', { name: 'Close image', exact: true }).click()
  }
  await page.getByRole('button', { name: 'Front', exact: true }).click()
  page.on('dialog', d => d.accept())
  await page.locator('input[type="file"]').setInputFiles({ name: 'front.png', mimeType: 'image/png', buffer: tinyImage })
  await expect(page.getByText('Photo saved privately to the selected week.', { exact: true })).toBeVisible()
  expect(state.photos).toHaveLength(10)
  expect(state.photos.some(p => p.id === '0-front')).toBeTruthy()
  expect(state.photos.some(p => p.id === '1-front')).toBeFalsy()
  await page.locator('.weekly-photo-pair figure').last().getByRole('button', { name: 'Delete this photo' }).click()
  await expect(page.getByText('Photo deleted. Other weeks are unchanged.', { exact: true })).toBeVisible()
  expect(state.photos).toHaveLength(9)
  expect(state.photos.some(p => p.id === '0-front')).toBeTruthy()
  await page.screenshot({ path: info.outputPath('weekly-photo-comparison.png'), fullPage: true })
  expect(state.errors).toEqual([])
})

test('nutrition prioritizes assigned portions and coach instructions; macro details are optional', async ({ page }, info) => {
  const state = progressFixture(); await mockProgress(page, 'client', state); await loginProgress(page)
  await nav(page).getByRole('button', { name: 'Nutrition', exact: true }).click()
  await expect(page.getByText('200 g', { exact: true })).toBeVisible()
  await expect(page.getByText('60 g', { exact: true })).toBeVisible()
  await expect(page.getByText('Eat before your morning session.', { exact: true })).toBeVisible()
  await expect(page.getByText('2200 kcal', { exact: false })).toBeHidden()
  await page.getByRole('button', { name: 'Followed', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Followed', exact: true })).toHaveAttribute('aria-pressed','true')
  expect(state.nutrition.meals[0].adherence_status).toBe('followed')
  await page.screenshot({ path: info.outputPath('meal-first-nutrition.png'), fullPage: true })
  expect(state.errors).toEqual([])
})
